# Generated by zero-downtime-cicd-template. Do not edit directly.
# service: {{service_name}}
# active_color: {{active_color}}
# active_upstream_port: {{active_upstream_port}}

upstream {{service_name}}_active {
    server 127.0.0.1:{{active_upstream_port}};
}

server {
    listen {{public_port}};
    server_name {{nginx_server_name}};

    location {{health_path}} {
        proxy_pass http://{{service_name}}_active;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Zero-Downtime-Service {{service_name}};
        proxy_set_header X-Zero-Downtime-Color {{active_color}};
    }

    location / {
        proxy_pass http://{{service_name}}_active;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Zero-Downtime-Service {{service_name}};
        proxy_set_header X-Zero-Downtime-Color {{active_color}};
    }
}
