# Generated by zero-downtime-cicd-template. Do not edit directly.
# service: {{service_name}}
# active_color: {{active_color}}
# active_upstream_port: {{active_upstream_port}}

<VirtualHost *:80>
    ServerName {{apache_server_name}}

    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:{{active_upstream_port}}/
    ProxyPassReverse / http://127.0.0.1:{{active_upstream_port}}/

    RequestHeader set X-Forwarded-Proto "http"
    RequestHeader set X-Zero-Downtime-Service "{{service_name}}"
    RequestHeader set X-Zero-Downtime-Color "{{active_color}}"
</VirtualHost>
